### ISSUE TITLE
Memory leak when using `set_predictions`

### ISSUE THREAD

**Issue by aboucaud** [paris-saclay-cds/ramp-backend#7]
The API method `set_predictions()`  to insert the predictions into the database seems to have some memory leakage as noted by Bertrand Rigaud. The amount of memory that is not released corresponds to the uncompressed size of both `y_pred_train` and `y_pred_test`. 

Using such method with threads therefore ends up quickly with a `MemoryError`.

Here is the `memory_profiler` output of the method:
```Line #    Mem usage    Increment   Line Contents
================================================
   130   51.184 MiB   51.184 MiB   @profile
   131                             def set_predictions(config, submission_id, prediction_path, ext='npy'):
   153                                 # Read config from external file
   154   51.211 MiB    0.027 MiB       conf = read_backend_config(config)
   155
   156                                 # Create database url
   157   51.211 MiB    0.000 MiB       db_url = URL(**conf['sqlalchemy'])
   158   63.246 MiB   12.035 MiB       db = create_engine(db_url)
   159
   160                                 # Create a configured "Session" class
   161   63.246 MiB    0.000 MiB       Session = sessionmaker(db)
   162
   163                                 # Link the relational model to the database
   164   64.691 MiB    1.445 MiB       Base.metadata.create_all(db)
   165
   166                                 # Connect to the dabase and perform action
   167   64.691 MiB    0.000 MiB       with db.connect() as conn:
   168   64.719 MiB    0.027 MiB           session = Session(bind=conn)
   169
   170   66.707 MiB    1.988 MiB           submission = select_submissions_by_id(session, submission_id)
   171
   172  383.648 MiB  313.848 MiB           for fold_id, cv_fold in enumerate(submission.on_cv_folds):
   173  380.555 MiB    0.000 MiB               pred_file = os.path.join(prediction_path,
   174  380.555 MiB    0.000 MiB                                        'fold_{}'.format(fold_id),
   175  380.555 MiB    0.000 MiB                                        'y_pred_{}.{}'.format('train', ext))
   177  537.203 MiB  156.648 MiB               y_train = np.load(pred_file)['y_pred']
   178  537.203 MiB    0.000 MiB               cv_fold.full_train_y_pred = y_train
   179
   182  537.203 MiB    0.000 MiB               pred_file = os.path.join(prediction_path,
   183  537.203 MiB    0.000 MiB                                        'fold_{}'.format(fold_id),
   184  537.203 MiB    0.000 MiB                                        'y_pred_{}.{}'.format('test', ext))
   186  694.184 MiB  156.980 MiB               y_test = np.load(pred_file)['y_pred']
   187  694.184 MiB    0.000 MiB               cv_fold.test_y_pred = y_test
   190
   191  694.184 MiB    0.000 MiB               cv_fold.valid_time = 0.0
   192  694.184 MiB    0.000 MiB               cv_fold.test_time = 0.0
   193  694.184 MiB    0.000 MiB               cv_fold.state = 'tested'
   194  383.648 MiB -310.535 MiB               session.commit()
   195
   196  383.648 MiB    0.000 MiB           submission.state = 'tested'
   197  383.707 MiB    0.059 MiB           session.commit()
   198
   199  383.707 MiB    0.000 MiB       del submission
```

So far I haven't been able to pinpoint the origin of the problem but posts such a [this one](https://stackoverflow.com/a/16117623) may suggest the use of ORM `relationship` and `backref` could play a role in "loosing" the reference to a Python object, which therefore won't be garbage collected.

**Comment by kegl** [comment]
But why would we call `set_predictions()` from a persisting process?

**Comment by aboucaud** [comment]
Well at the time he decided to use a queue and threads to manage multiple incoming submissions.
Now he just embedded this `set_predictions()` in a process to get rid of the memory leakage.

**Comment by bertrandrigaud** [comment]
The problem is the same with set_submission_state but it is less visible

**Comment by aboucaud** [comment]
With the help of @ogrisel we managed to get a hold on the problem that originated from `sqlalchemy`.

`dict_keys` reference were preventing the parameter values to be garbage collected.

Now waiting for the PR zzzeek/sqlalchemy#441 to be merged.

**Comment by glemaitre** [comment]
The PR has been merged ;)

**Comment by aboucaud** [comment]
Alright, @bertrandrigaud for now let's switch the the master version of sqlalchemy (instead of my fork)

**Comment by glemaitre** [comment]
@aboucaud Is the fix of sqlalchemy solved the issue at some point.
We are still seeing the same issue whenever we access a back-reference: https://github.com/paris-saclay-cds/ramp-board/issues/190

**Comment by aboucaud** [comment]
Yes it did. @ogrisel wrote the tests and the fix on `sqlalchemy` and it was merged quite quickly.

The bug came from an error left when adding PY3 compatibility. At some point in the code when creating the tree, a reference to a dictionary keys made it impossible for the GC to free the objects in memory. 
If I remember correctly, the fix was to replace `dict.keys()` by `list(dict.keys())`.

**Comment by aboucaud** [comment]
Sorry @glemaitre, just read through the whole bunch of new issues, you're totally aware of everything I just mentioned 😄. 
So to the best of my knowledge, the leak we had at the time was indeed fixed.
